// src/frontend-angular/src/app/shared/build-version.component.ts
import { Component, computed, input } from '@angular/core'
import { formatBuildInfo, type BuildInfo } from '../core/build-info'

@Component({
  selector: 'app-build-version',
  standalone: true,
  template: `
    <span>{{ component() }} </span>
    @if (version(); as version) {
      @if (version.runUrl) {
        <a
          [href]="version.runUrl"
          target="_blank"
          rel="noopener noreferrer"
          [attr.aria-label]="component() + ' ' + version.label + ' — ouvrir le run GitHub Actions'"
          >{{ version.label }}</a
        >
      } @else {
        <span>{{ version.label }}</span>
      }
      @if (version.details) {
        <details>
          <summary>Détails {{ component() }}</summary>
          <span>{{ version.details }}</span>
        </details>
      }
    } @else {
      <span>{{ status() }}</span>
    }
  `,
  styles: [
    `
      :host {
        display: block;
        overflow-wrap: anywhere;
      }
      a {
        color: inherit;
        text-decoration: underline;
      }
      details {
        margin-top: 0.2rem;
      }
      summary {
        cursor: pointer;
      }
    `,
  ],
})
export class BuildVersionComponent {
  readonly component = input.required<string>()
  readonly info = input<BuildInfo | null>(null)
  readonly status = input('')
  readonly version = computed(() => {
    const info = this.info()
    return info ? formatBuildInfo(info) : null
  })
}

// src/frontend/src/components/BuildVersion.vue
<script setup lang="ts">
import { computed } from 'vue'
import { formatBuildInfo, type BuildInfo } from '@/utils/buildInfo'

const props = defineProps<{ component: string; info?: BuildInfo | null; status?: string }>()
const version = computed(() => (props.info ? formatBuildInfo(props.info) : null))
</script>

<template>
  <div class="build-version">
    <span>{{ component }} </span>
    <template v-if="version">
      <a
        v-if="version.runUrl"
        :href="version.runUrl"
        target="_blank"
        rel="noopener noreferrer"
        :aria-label="`${component} ${version.label} — ouvrir le run GitHub Actions`"
        >{{ version.label }}</a
      >
      <span v-else>{{ version.label }}</span>
      <details v-if="version.details">
        <summary>Détails {{ component }}</summary>
        <span>{{ version.details }}</span>
      </details>
    </template>
    <span v-else>{{ status }}</span>
  </div>
</template>

<style scoped>
.build-version {
  overflow-wrap: anywhere;
}
a {
  color: inherit;
  text-decoration: underline;
}
details {
  margin-top: 0.2rem;
}
summary {
  cursor: pointer;
}
</style>
